trailing_comma    = "Never"
use_try_shorthand = true
wrap_comments     = true
match_block_trailing_comma = true
condense_wildcard_suffices = true

reorder_imports          = true
reorder_imported_names   = true
reorder_imports_in_group = true

format_strings = true
max_width      = 100
