version: "3"

services:
  example:
    build: .
    networks: # Workaround, see below
      - default

# When a VPN is enabled, docker-compose refuses to work. This bypasses that by
# creating a separate docker network that somehow works better.
networks:
  default:
    ipam:
      config:
        # TODO: Update    |
        #       0-255     V
        - subnet: 192.168.9.0/24
